### ISSUE TITLE
Ability to use terraform after spinning up infra

### ISSUE THREAD

**Issue by superseb** [rancherlabs/corral#13]
Having a way to create standardized infra and (HA) cluster for Rancher is step 1, but step 2 should be using the rancher2 terraform provider. This will ensure that we use (and thus test) our own tools (dog-fooding) and that we create sharable Terraform code versus our own formatted shell scripts with retries/workarounds that should really be fixed in the provider. This will also eliminate the x amount of ways things are done today (shell/terraform/python/go etc)

**Comment by paynejacob** [comment]
I think this could be accomplished by adding support for executing a tf module similar to how commands work.

```
steps:
	- tf_module: nodes
	- command: install-rancher.sh
	   node_pools:
	     - install-rancher.sh
	 - tf_module: rancher-config
```

**Comment by paynejacob** [comment]
This will be accomplished by allowing packages to install other packages.

the additional packages will be defined in the commands section of the package manifest.

you can optionally disable terraform destroy on cleanup for packages.

as part of this work we need to add logic to skip running terraform if no module exists in the package.

packages will be deleted in reverse of the order they appear in the manifest
