### ISSUE TITLE
Script failures

### ISSUE THREAD

**Issue by paynejacob** [rancherlabs/corral#23]
there should be a script command similar to `corral_set` to report an error and cancel the creation of a corral.

**Comment by paynejacob** [comment]
Corral should check command exit codes, in addition to this.

**Comment by paynejacob** [comment]
In addition to the command we should also be checking exit codes on command

**Comment by jakefhyde** [comment]
@paynejacob I'm thinking something like `corral_exit code=1 message="some message"`, defaulting to 1 and `script exited with code <code>`, thoughts?

**Comment by paynejacob** [comment]
I think we can rely on the scripts exit codes the I was thinking of the `corral_exit` command as more of a log.Fatal.  It allows you to send a message to the user.
