### ISSUE TITLE
Build a new release as the current v1.0.0 is old not including the latest fixes

### ISSUE THREAD

**Issue by izaac** [rancherlabs/corral#85]
For example this fix is not in the latest release.
https://github.com/rancherlabs/corral/pull/70

Also could we have the release/build process documented somewhere, like internal documentation?

**Comment by jakefhyde** [comment]
@izaac corral v1.1.0 is now out: https://github.com/rancherlabs/corral/releases/tag/v1.1.0, I'll be adding more developers docs next week

**Comment by izaac** [comment]
Thanks! closing. I was even able to execute the script in the remote now.
